### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Joe-Downs** [jsquyres/ompi#17]
Issue: [The server crashes if a user's password is a resolvable URL.](https://xkcd.com/1700/)

**Comment by jsquyres** [comment]
Noice!

Let me assign the "needs-reply" label. 

@Joe-Downs If you reply, it should automatically remove that label.  Can you try?

**Comment by Joe-Downs** [comment]
Yes, I can try.

**Comment by jsquyres** [comment]
Noice. It worked.

Ok, I'm going to put needs-reply back on here, and let's see what happens when this times out in a day.
