### ISSUE TITLE
Like this?

### ISSUE THREAD

**Issue by Joe-Downs** [jsquyres/ompi#20]
Please submit all the information below so that we can understand the working environment that is the context for your question.

* If you have a problem building or installing Open MPI, [be sure to read this](https://docs.open-mpi.org/en/main/getting-help.html#for-problems-building-or-installing-open-mpi).
* If you have a problem launching MPI or OpenSHMEM applications, [be sure to read this](https://docs.open-mpi.org/en/main/getting-help.html#for-problems-launching-mpi-or-openshmem-applications).
* If you have a problem running MPI or OpenSHMEM applications (i.e., after launching them), [be sure to read this](https://docs.open-mpi.org/en/main/getting-help.html#for-problems-running-mpi-or-openshmem-applications).

### Please describe the system on which you are running

* Operating system/version:
* Computer hardware:
* Network type:

-----------------------------

## Details of the problem

Please describe, in detail, the problem that you are having, including the behavior you expect to see, the actual behavior that you are seeing, steps to reproduce the problem, etc.  It is most helpful if you can attach a small program that a developer can use to reproduce your problem.

**Note**: If you include verbatim output (or a code block), please use a [GitHub Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) code block like below:
```shell
shell$ mpirun -n 2 ./hello_world
```

**Comment by jsquyres** [comment]
Thanks.  Let's make sure the "remove needs-reply" bot still works...

**Comment by Joe-Downs** [comment]
Add your comment here...

**Comment by jsquyres** [comment]
Cool; I didn't break it. 😄 Let's let this issue go stale overnight, and get closed another day later...

**Comment by Joe-Downs** [comment]
Leave a comment

**Comment by jsquyres** [comment]
Thanks.  Let's see if we got the action logic correct this time; re-added the needs-reply label. That should make this go stale and then auto-close.
