### ISSUE TITLE
This is a test issue

### ISSUE THREAD

**Issue by ompiteam** [jsquyres/ompi#21]
We'll post something here to test the bots.

**Comment by jsquyres** [comment]
Test replty.

**Comment by ompiteam** [comment]
Here's a reply.

**Comment by ompiteam** [comment]
reply again

**Comment by ompiteam** [comment]
reply 3

**Comment by jsquyres** [comment]
Hello world

**Comment by jsquyres** [comment]
Let's go stale waiting for user reply

**Comment by ompiteam** [comment]
Renamed the labels -- let's make sure I didn't break anything...

**Comment by jsquyres** [comment]
Cool.  Didn't break anything.  Ok, let's let this go stale.
